#
# Process UNFPA income data, convert into income shares, and apply to expenditure
# data to estimate total outflow by source.
#
#
#
# NOTES
#
# UNFPA is funded from voluntary contributions that are either unrestricted as to
# use (referred to as "unearmarked", "core" or "regular" resources) or restricted
# by the donors for a specific purpose, programme or activity (referred to as 
# "earmarked" or "non-core" resources). 
# 
# A smaller portion also comes from "other revenue":
# This category mainly comprises cost-recovery charges, net
# foreign exchange gains and income generated by investments. The cost-recovery
# charges include indirect cost-recovery charges on disbursements funded from
# earmarked resources, fees earned by UNFPA for performing administrative agent
# functions and procurement services handling fees. 
#
code_repo <- 'FILEPATH'


report_year <- 2024

source(paste0(code_repo, "/FGH_", report_year, "/utils.R"))


UNFPA_DIR <- "FILEPATH"

process_contributions <- function(data_year) {
    dc <- data.table()
    fp <- file.path(
        UNFPA_DIR,
        "RAW",
        "INCOME",
        paste0("donor_contributions_", data_year, ".xlsx")
    )
    start_yr <- strsplit(as.character(data_year), "_")[[1]][1]
    
    sheets <- openxlsx::getSheetNames(fp)
    sheets <- base::intersect(c("unearmarked", "earmarked", "special_funds"), sheets) 
    if (start_yr <= 2000) sheets <- "Sheet1"
    for (sh in sheets) {
        tab <- openxlsx::read.xlsx(fp, sheet = sh)
        names(tab) <- c("donor", "amount")
        tab$type <- sh
        dc <- rbind(dc, tab)
    }
    dc[type == "Sheet1", type := "unearmarked"]
    
    
    # clean donor name
    dc[, donor := trimws(donor)]
    ## remove all whitespace characters other than spaces
    dc[, donor := gsub("[\t\n\r]", " ", donor)]
    ## convert spaces more than one to a single space
    dc[, donor := gsub(" {2,}", " ", donor)]
    
    dc <- dc[! tolower(donor) %in% c("trust funds", "sepcial funds", "donor",
                                     "government")]
    
    if (start_yr > 2000) {
        # fix rows where donor name was multi-line so cell value was split, e.g.,
        # ----------------------------------------------------|
        # United Kingdom of Great Britan  |   <blank>         |
        # --------------------------------|-------------------|
        # and Northern Ireland            |   <amount value>  |
        # ----------------------------------------------------|
        # (note, 0 values are represented as a "-" so we can identify these cases from
        # where the amount values are blank - or NA after parsed by R)
        dc[amount == "", amount := NA_character_]
        dc[, amnt_na_l1 := shift(is.na(amount), n = 1, type = "lag")]
        dc[, donor_l1 := shift(donor, n = 1, type = "lag")]
        dc[amnt_na_l1 == TRUE,
           donor := paste(trimws(donor_l1), trimws(donor))]
        dc <- dc[!is.na(amount)]
        dc[, c("amnt_na_l1", "donor_l1") := NULL]
        #
        # years pre-2000 were hand extracted and thus this issue is not
        # relevant
    }
        
    # parse amount column into numeric
    ## convert numbers like (1000) to -1000
    dc[grepl("^\\(", amount),
       amount := gsub("\\)", "", gsub("\\(", "-", amount))]
    ## remove non-numeric characters
    dc[, amount := gsub("[^0-9.-]", "", amount)]
    dc[amount == "-", amount := ""]
    ## now can drop any blanks - those were entirely non-numeric, not values we need
    dc <- dc[amount != ""]
    dc[, amount := as.numeric(amount)]
    if (start_yr > 2000)
        dc[, amount := amount * 1000] # convert from 1000s of USD
    return(dc)
}


#
# Load donor contributions ====================================================
#
contrib <- data.table()
for (yr in c(
    "1990_1991", "1992_1993", "1994_1995", "1996_1997", "1998_1999",
    "2000_2001", "2002_2003", "2004_2005", "2006_2007", "2008_2009",
    "2010_2011", 2012:(report_year - 1))
    ) {
    dt <- process_contributions(yr)
    dt[, year := yr]
    contrib <- rbind(contrib, dt)
}

contrib[, type := fifelse(type == "unearmarked", "regular", "other")]
contrib <- contrib[, .(amount = sum(amount)), by = .(year, type, donor)]



#
# Clean donor names / categorize ==============================================
#
ddb <- fread(get_path("meta", "donor", "income_sector_and_type_assignments.csv"),
             encoding = "Latin-1")
ddb[, donor_clean := string_to_std_ascii(DONOR_NAME, pad_char = "")]
ddb <- unique(ddb[, .(donor_clean, INCOME_SECTOR, INCOME_TYPE, ISO_CODE)])


contrib[, donor_clean := string_to_std_ascii(donor, pad_char = "")]
contrib <- merge(contrib, ddb, by = "donor_clean", all.x = TRUE)
contrib[donor_clean %like% "^MULTI DONOR", `:=`(
    INCOME_SECTOR = "OTHER", INCOME_TYPE = "OTHER", ISO_CODE = NA
)]
contrib[donor_clean %in% c(
    "PRIVATE ENDOWMENT TRUST", "US TAX REFUND"
    ), `:=`(
    INCOME_SECTOR = "OTHER", INCOME_TYPE = "OTHER", ISO_CODE = NA
)]

x <- standardize_donors(
    contrib,
    col_to_change = "donor_clean",
    reference = get_path("meta", "donor", "income_sector_and_type_assignments.csv")
)
matches <- x[[2]][!is.na(BEST_MATCH_NAME)]
contrib <- merge(contrib,
                 matches[!is.na(BEST_MATCH_NAME),
                         .(DONOR_NAME, INCOME_SECTOR, INCOME_TYPE, ISO_CODE)],
                 by.x = "donor_clean", by.y = "DONOR_NAME",
                 all.x = TRUE,
                 suffixes = c("", "_new"))
contrib[!is.na(INCOME_SECTOR_new), `:=`(
    INCOME_SECTOR = INCOME_SECTOR_new,
    INCOME_TYPE = INCOME_TYPE_new,
    ISO_CODE = ISO_CODE_new
)]
contrib[, c("INCOME_SECTOR_new", "INCOME_TYPE_new", "ISO_CODE_new") := NULL]


if (contrib[is.na(INCOME_SECTOR), .N] > 0)
    stop("Some donors are not categorized. Update databases as needed.")


contrib[ISO_CODE == "", ISO_CODE := NA_character_]
contrib <- contrib[, .(amount = sum(amount)),
                   by = .(year, type,
                          DONOR_NAME = donor_clean,
                          INCOME_SECTOR, INCOME_TYPE, ISO_CODE)]

## merge on donor country
locs <- fread(get_path("meta", "locs", "fgh_location_set.csv"))
contrib <- merge(contrib,
                 locs[, .(ISO_CODE = ihme_loc_id, DONOR_COUNTRY = location_name)],
                 by = "ISO_CODE", all.x = TRUE)


#
# Add UNFPA other revenue =====================================================
#
other_revenue <- openxlsx::read.xlsx(
    file.path(UNFPA_DIR, "RAW", "INCOME", "unfpa_other_revenue.xlsx")
)
setDT(other_revenue)
other_revenue <- other_revenue[, .(year = YEAR,
                                   type = "other",
                                   amount = OTHER_REVENUE,
                                   DONOR_NAME = "OTHER_REVENUE_EXTRACTED",
                                   DONOR_COUNTRY = NA,
                                   INCOME_SECTOR = "OTHER",
                                   INCOME_TYPE = "OTHER",
                                   ISO_CODE = NA)]
other_revenue <- other_revenue[!is.na(amount)]

if (other_revenue[, length(unique(year))] != contrib[, length(unique(year))])
    stop("Ensure that both 'other revenue' and donor contributions have been extracted for all years")

contrib <- rbind(contrib, other_revenue)

## explode biennium years
contrib <- contrib[, .(year = unlist(strsplit(year, split = "_"))),
                   by = names(contrib[, -"year"])]
setorder(contrib, year)





#
# Calculate income shares =====================================================
#
## note - if the donor's contribution is negative, we can assume that they
## shouldn't be considered a contributor for the given year, so we drop
contrib <- contrib[amount > 0]

## in years before 2010, we don't have earmarked contributions so pool all 
## funds together
contrib_pre <- contrib[year < 2010]
contrib_pre <- contrib_pre[, .(amount = sum(amount)),
                           by = .(year, ISO_CODE, DONOR_NAME,
                                  INCOME_SECTOR, INCOME_TYPE, DONOR_COUNTRY)]
contrib_pre[, type := "all"]
contrib <- rbind(
    contrib_pre,
    contrib[year >= 2010]
)

contrib[, annual_tot := sum(amount), by = .(year, type)]

contrib[, donor_share := amount / annual_tot]


#
# Load expenditure ============================================================
#
expend <- data.table(readstata13::read.dta13(
    file.path(
        UNFPA_DIR, "INT", paste0("FGH_", report_year), "INC_EXP_INITIAL.dta"
    )
))
expend <- expend[, .(
    regular = sum(EXP_REG, na.rm = TRUE),
    other = sum(EXP_TRUST + EXP_JPOs + EXP_OTHER, na.rm = TRUE)
), by = YEAR]
## in years before 2010, we don't have earmarked contributions, so we pool all
expend[YEAR < 2010, `:=`(all = regular + other, regular = NA, other  = NA)]
expend <- melt(expend[YEAR < 2023],
               id.vars = "YEAR",
               variable.name = "type",
               value.name = "OUTFLOW")
expend <- expend[!is.na(OUTFLOW)]



for (yr in seq(2023, report_year - 1)) {
    new <- fread(file.path(
        UNFPA_DIR, "RAW", paste0("UNFPA_Audited_Financial_report_", yr,".csv")
    ))
    new[, EXP_REG := as.numeric(gsub(",", "", EXP_REG))]
    new[, EXP_TRUST := as.numeric(gsub(",", "", EXP_TRUST))]
    new <- new[, .(
        regular = sum(EXP_REG, na.rm = TRUE),
        other = sum(EXP_TRUST, na.rm = TRUE)
    ), by = YEAR]
    new <- melt(new, id.vars = "YEAR", variable.name = "type", value.name = "OUTFLOW")
    expend <- rbind(expend, new)
}


#
# Disaggregate expenditure by source ==========================================
#
contrib[, `:=`(YEAR = as.integer(year), year = NULL)]
inc_exp <- merge(contrib, expend, by = c("YEAR", "type"), all.x = TRUE)

if(inc_exp[is.na(OUTFLOW), .N] > 0)
    stop("Some years/budget-types in the income data do not have expenditure data. Check the data.")

inc_exp[, OUTFLOW := OUTFLOW * donor_share]

inc_exp[, CHANNEL := "UNFPA"]

#
# Save INC_EXP ================================================================
#
setorder(inc_exp, YEAR)
fwrite(
    inc_exp,
    file.path(
        UNFPA_DIR, "FIN", paste0("FGH_", report_year), "INC_EXP_FINAL.csv"
    )
)

message("Done.")

