#----# Docstring #----# ####
# Project:  FGH
# Purpose:  Validation/troubleshooting functions to compare WHO datasets
#---------------------# ####

#----# Environment Prep #----# ####
rm(list=ls(all.names = TRUE))

if (!exists("code_repo"))  {
  code_repo <- 'FILEPATH'
}

report_year <- 2024

source(paste0(code_repo, "/FGH_", report_year, "/utils.R"))
pacman::p_load(crayon, stringr, readstata13, readxl, dplyr)

# Variable prep
donors <- paste0(dah.roots$j, 'FILEPATH')
int <- get_path("who", "int")
int_old <- paste0(dah.roots$j, 'FILEPATH')
DATA_YEAR <- dah.roots$report_year - 1
#----------------------------# ####


cat('\n\n')
cat(green(' ###########################################\n'))
cat(green(' ####          LOAD WHO DONORS          ####\n'))
cat(green(' ###########################################\n\n'))
who <- fread(paste0(int,"WHO_INCOME_SECTOR_TYPE_FIX_", dah.roots$report_year, ".csv"))
ref <- fread(paste0(int_old,"WHO_INCOME_SECTOR_TYPE_FIXED.csv"))

who[, upper_DONOR_NAME := string_to_std_ascii(DONOR_NAME)]
who_old <- who %>%
  filter(YEAR != DATA_YEAR)

dt_sd <- standardize_donors(who_old, 'DONOR_NAME')
dt_donor <- dt_sd[[1]]
dt_not_match <- dt_sd[[2]]
dt_donor[, IHME_NAME := NULL]
setnames(dt_donor, "DONOR_NAME", "original_DONOR_NAME")
setnames(dt_donor, "checked_upper_DONOR_NAME",'DONOR_NAME')
dt_donor$DONOR_NAME_upper <- dt_donor$DONOR_NAME

dt_donor <- dt_donor %>% 
  select(names(ref))

who_ry <- who %>%
  filter(YEAR == DATA_YEAR) %>%
  rename(original_DONOR_NAME = DONOR_NAME) %>%
  mutate(DONOR_NAME = toupper(original_DONOR_NAME)) %>%
  mutate(DONOR_NAME_upper = DONOR_NAME) %>%
  select(names(ref))

final <- rbind(dt_donor, who_ry)

final[DONOR_NAME == "NA",
      DONOR_NAME := iconv(original_DONOR_NAME, from = "latin1", to = "UTF8")]
final[, DONOR_NAME := string_to_std_ascii(DONOR_NAME, pad_char = "")]


final[DONOR_NAME %in% c(
    "CA TE DA IVOIRE",
    "CA TE DAEUR TM IVOIRE",
    "COTE D IVOIRE",
    "DEMOCRATIC PEOPLEA S REPUBLIC OF KOREA",
    "DEMOCRATIC PEOPLEAEUR TM S REPUBLIC OF KOREA",
    "DEMOCRATIC PEOPLE S REPUBLIC OF KOREA",
    "HONG KONG SAR PEOPLEA S REPUBLIC OF CHINA",
    "HONG KONG SAR PEOPLEAEUR TM S REPUBLIC OF CHINA",
    "HONG KONG SAR PEOPLE S REPUBLIC OF CHINA",
    "THE GOVERNMENT OF HONG KONG SAR PEOPLE S",
    "IRAN ISLAMIC REPUBLIC OF A",
    "LAO PEOPLEAEUR TM S DEMOCRATIC REPUBLIC",
    "LAO PEOPLE S DEMOCRATIC REPUBLIC",
    "FRANCE UNION NATIONALE DES CAISSES D ASSURANCE MALADIE UNCAM",
    "MACAO SAR PEOPLEA S REPUBLIC OF CHINA",
    "MACAO SAR PEOPLEAEUR TM S REPUBLIC OF CHINA",
    "MACAO SAR PEOPLE S REPUBLIC OF CHINA",
    "THE GOVERNMENT OF MACAO SAR PEOPLE S REPUBLIC OF CHINA",
    "SUDANA",
    "TA 1 4 RKIYE",
    "TA RKIYE",
    "FRANCE 2006 2007",
    "ISRAEL 2006 2007",
    "KUWAIT 2006 2007"
), `:=`(
    INCOME_SECTOR = "PUBLIC",
    INCOME_TYPE = "CENTRAL"
)]

final[DONOR_NAME %in% c(
    "EMILIA ROMAGNA ITALY",
    "LA MA C TROPOLE GRAND LYON FRANCE",
    "REGIONAL GOVERNMENT OF PUGLIA ITALY",
    "REGIONE LAZIO ITALY",
    "CONSEIL GENERAL DU RHONE",
    "COMMUNAUTE URBAINE DE LYON",
    "LA METROPOLE GRAND LYON FRANCE"
), `:=`(
    INCOME_SECTOR = "PUBLIC",
    INCOME_TYPE = "LOCAL"
)]


final[DONOR_NAME %in% c(
    "AFRICAN UNION AEUR UNITED NATIONS HYBRID OPERATION IN DARFUR",
    "AFRICAN UNION UNITED NATIONS HYBRID OPERATION IN DARFUR",
    "HQ DEPARTMENT OF HEALTH WORKFORCE HWF",
    "HQ DEPARTMENT OF PRIMARY HEALTH CARE PHC",
    "REGIONAL OFFICE FOR EUROPE RGO EURO",
    "REGIONAL OFFICE FOR THE WESTERN PACIFIC RGO WPRO",
    "UN REGIONAL DIRECTOR ESA",
    "UNITED NATIONS ECONOMIC",
    "UNITED NATIONS ENTITY FOR GENDER EQUALITY AND THE EMPOWERMENT",
    "UNITED NATIONS HIGH",
    "UNITED NATIONS PEACE AND DEVELOPMENT TRUST FUND",
    "UNITED NATIONS POSTAL ADMINISTRATION UNPA",
    "UNITED NATIONS RESIDENT COORDINATOR UNRCO INDIA",
    "UNITED NATIONS CHILDREN S FUND UNICEF",
    "UNITED NATIONS DEVELOPMENT GROUP UNDG IRAQ TRUST FUND",
    "PHILIPPINES 2006 2007",
    "PORTUGAL 2006 2007"
), `:=`(
    INCOME_SECTOR = "OTHER",
    INCOME_TYPE = "UN"
)]


final[DONOR_NAME %in% c(
    "ACTED",
    "AMERICAN ACADEMY OF OTOLARYNGOLOGY HEAD AND NECK SURGERY",
    "AMERICAN SOCIETY FOR CLINICAL PATHOLOGY",
    "ASIAAEUR EUROPE FOUNDATION ASEF",
    "CHILDHOOD CANCER INTERNATIONAL CCI",
    "ECONOMIC RESEARCH INSTITUTE FOR ASEAN EAST ASIA ERIA",
    "ENABLEME",
    "FAMINE RELIEF FUND",
    "FUNDACIA N MUNDO SANO SPAIN",
    "FUNDACIA SUPPORT GIRONA",
    "GLOBAL HEALTH DEVELOPMENT",
    "HEPATITIS FUND",
    "INSTITUTE OF LIVING",
    "INTERNATIONAL RENEWABLE ENERGY AGENCY IRENA",
    "INTOSAI DEVELOPMENT INITIATIVE IDI",
    "IODINE GLOBAL NETWORK",
    "MALE CONTRACEPTIVE INITIATIVE MCI",
    "ST JUDE CHILDRENA S RESEARCH HOSPITAL",
    "ST JUDE CHILDRENAEUR TM S RESEARCH HOSPITAL",
    "WORLD FEDERATION OF CHIROPRACTIC WFC",
    "WORLD FEDERATION OF OCCUPATIONAL THERAPISTS WFOT",
    "WORLD PHYSIOTHERAPY",
    "FUNDACIA3N ANESVAD",
    "FUNDACIA3N PROBITAS",
    "FUNDACION MUNDO SANO SPAIN",
    "JAPAN DENTAL ASSOCIATION",
    "TASK FORCE SIGHT AND LIFE",
    "CONSEIL EUROPEEN DE L INDUSTRIE CHIMIQUE",
    "ISTITUTO DI RICOVERO E CURA A CARATTERE SCIENTIFICO IRCCS OASI MARIA",
    "NETSPEAR NETWORK FOR SURVEILLANCE OF PNEUMOCOCCAL DISEASES IN THE EAST AFRICAN REGION",
    "MILLENNIUM CHALLENGE ACCOUNT MONGOLIA",
    "THE BONE AND JOINT DECADE 2000 2010",
    "INTERNATIONAL TUBERCULOSIS RESEARCH CENTER KOREA ITRC"
), `:=`(
    INCOME_SECTOR = "PRIVATE",
    INCOME_TYPE = "NGO"
)]

final[DONOR_NAME %in% c(
    "CLEAN AIR FUND",
    "KOREAN FOUNDATION FOR INTERNATIONAL HEALTHCARE AEUR DR LEE JONG WOOK MEMORIAL FUND KOFIH",
    "KOREAN FOUNDATION FOR INTERNATIONAL HEALTHCARE DR LEE JONG WOOK MEMORIAL",
    "KOREAN FOUNDATION FOR INTERNATIONAL HEALTHCARE DR LEE JONG WOOK MEMORIAL FUND KOFIH",
    "KOREAN FOUNDATION FOR INTERNATIONAL HEALTHCARE KFIH DR LEE JONG WOOK MEMORIAL FUND",
    "SAFARICOM FOUNDATION",
    "TRUSTEES OF COLUMBIA UNIVERSITY IN THE CITY OF NEW YORK",
    "FONDATION MERIEUX"
), `:=`(
    INCOME_SECTOR = "PRIVATE",
    INCOME_TYPE = "FOUND"
)]


final[DONOR_NAME %in% c(
    "UNIVERSITEIT GENT",
    "UNIVERZITA KARLOVA",
    "TOKYO WOMEN S MEDICAL SCHOOL",
    "CENTRO STUDI E RICERCHE SALUTE I NTALE",
    "CENTRE D ETUDE DE L ENERGIE NUCLEAIRE",
    "ISTITUTO NAZIONALE NEUROLOGICO CARLO BESTA"
), `:=`(
    INCOME_SECTOR = "PUBLIC",
    INCOME_TYPE = "UNIV"
)]

final[DONOR_NAME %in% c(
    "FONDAZIONE TELECOM ITALIA",
    "LORING WOLCOTT COOLIDGE TRUST LLC",
    "REAL ESTATE FUND PROXY DONOR",
    "SOLARSACK APS",
    "RHONE POULENC RORER SA",
    "UNITAR CHEMICAL AND WASTE MANAGEMENT"
), `:=`(
    INCOME_SECTOR = "INK",
    INCOME_TYPE = "CORP"
)]

final[DONOR_NAME %in% c(
    "ESTATE OF MR JERRY LYLE BABER",
    "ESTATE OF RITA SUSAN COOPER"
), `:=`(
    INCOME_SECTOR = "PRIVATE",
    INCOME_TYPE = "INDIV"
)]


final <- final[! DONOR_NAME %in% c(
    "NOTE 3", "MEMBERS AND ASSOCIATE MEMBERS"
)]

final[DONOR_NAME %ilike% "EUROPEAN COMMISSION", `:=`(
    INCOME_SECTOR = "OTHER", INCOME_TYPE = "EC", ISO_CODE = ""
)]

cat('  Save Dataset\n')
#----# Save Dataset #----# ####
fwrite(final, paste0(int,"WHO_INCOME_SECTOR_TYPE_FIXED_", dah.roots$report_year, ".csv"))